version: "3.9"
services:
  postgres:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  question-portal:
    build: .
    depends_on:
      - postgres
    links:
      - postgres
    ports:
      - "8080:8080"